version: '2.4'

x-limits: &limits
    pids_limit: 1024
    cpu_shares: 256
    mem_limit: 512m
    logging:
        options:
            max-size: 10m
            max-file: '3'

services:
    actor:
        <<: *limits
        build: ./actor
        image: naumachia/shellboi.actor
        restart: unless-stopped
        networks:
            default:
                ipv4_address: 172.30.0.5
        
    director:
        <<: *limits
        build: ./director
        image: naumachia/shellboi.director
        restart: unless-stopped
        environment: 
            - OWN_IP=172.30.0.8
            - ACTOR_IP=172.30.0.5
        networks:
            default:
                ipv4_address: 172.30.0.8
        depends_on:
            - actor

networks:
    default:
        driver: l2bridge
        ipam:
            driver: static
            config:
                - subnet: 172.30.0.0/28
