version: '2.4'

x-limits: &limits
    pids_limit: 1024
    cpu_shares: 256
    mem_limit: 512m
    logging:
        options:
            max-size: 10m
            max-file: '3'

services:
    sender:
        <<: *limits
        build: ./sender
        image: naumachia/sender.actor
        environment:
          - PLAYER_IP=172.30.0.14
          - CTF_FLAG=inctf{s0_y0u_finally_d3cid3d_t0_listen!!}
        networks:
            default:
                ipv4_address: 172.30.0.8
        restart: unless-stopped

networks:
    default:
        driver: l2bridge
        ipam:
            driver: static
            config:
                - subnet: 172.30.0.0/28