version: '2.4'

x-limits: &limits
    pids_limit: 1024
    cpu_shares: 256
    mem_limit: 512m
    logging:
        options:
            max-size: 10m
            max-file: '3'

services:
    web:
        <<: *limits
        build: ./web
        image: naumachia/buggy.web
        restart: unless-stopped
        ports:
            - 8000:8080
        networks:
            default:
                ipv4_address: 172.30.0.5

networks:
    default:
        driver: l2bridge
        ipam:
            driver: static
            config:
                - subnet: 172.30.0.0/28
