version: "3"
services:
    www:
        build: .
        ports:
            - "8001:80"
        volumes:
            - ./www1:/var/www/html/
        networks:
            - default
volumes:
    persistent: